version: '3.5'

services:
  # rockmongo:
  #   container_name: rockmongo
  #   image: 'webts/rockmongo:latest'
  #   environment:
  #     - MONGO_SERVERS=mongodb:27017
  #   ports:
  #     - '8080:80'
  #   depends_on:
  #     - mongodbmanager
  #   networks:
  #     - app-tier

  mongodb:
    container_name: mongodb_second
    image: 'mongodb:latest'
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin123
      - MONGODB_DATABASE=northwind_db
    volumes:
      - mongodb_data:/mongodb
    ports:
      - '27020:27017'
    depends_on:
      - mongodb
    networks:
      - app-tier

  mysql:
    container_name: mysql_server
    image: 'mysql:latest' 
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=northwind_db
    volumes:
      - mysql_data:/var/lib/mysql 
    ports:
      - '3306:3306'
    networks:
      - app-tier

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - MYSQL_HOST=mysql 
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '8081:80'

networks:
  app-tier:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mysql_data:
