version: '3.5'

services:
  rockmongo:
    container_name: rockmongo
    image: 'webts/rockmongo:latest'
    environment:
      - MONGO_SERVERS=mongodb:27017
    ports:
      - '8080:80'
    networks:
      - app-tier

  mongodb:
    container_name: mongodb
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=northwind_db
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27020:27017'
    networks:
      - app-tier
    restart: unless-stopped

  mysql:
    container_name: mysql_server
    image: 'mysql:latest' 
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=northwind_db
    volumes:
      - mysql_data:/var/lib/mysql 
    ports:
      - '3306:3306'
    networks:
      - app-tier
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"

networks:
  app-tier:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mysql_data:
